name: MyBB Documentation
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
baseurl: ""
mainsiteurl: https://mybb.com

gems:
  - jekyll-redirect-from

exclude: ["CNAME", "README.md", "CONTRIBUTING.md", "key_private.key", "key_public.pem"]